name: test-list-working-dirs

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
    - uses: aquaproj/aqua-installer@a34cc75221784a96e3caf4bbf716ff67a160a3f1 # v1.0.0
      with:
        aqua_version: v1.17.1
    - uses: ./list-working-dirs
      id: working_dirs
      env:
        TFACTION_CONFIG: list-working-dirs/tests/tfaction-root.yaml
    - run: cat "${{ steps.working_dirs.outputs.file }}"
